// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1e9WAJE5Hl42TY2L4DoFAA_IAGWo-pfs',
    appId: '1:404568858266:web:9ee2dbda72d0f9c9234923',
    messagingSenderId: '404568858266',
    projectId: 'chattr-da2b5',
    authDomain: 'chattr-da2b5.firebaseapp.com',
    storageBucket: 'chattr-da2b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOQlzclIFtNY4ehR6b-ipiOotZn5IBBFg',
    appId: '1:404568858266:android:3e0079dd273253b0234923',
    messagingSenderId: '404568858266',
    projectId: 'chattr-da2b5',
    storageBucket: 'chattr-da2b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZm6B27I1xRFVZM9lBpk7C1RPCfxJtVig',
    appId: '1:404568858266:ios:9d73521b3dbd9187234923',
    messagingSenderId: '404568858266',
    projectId: 'chattr-da2b5',
    storageBucket: 'chattr-da2b5.firebasestorage.app',
    iosBundleId: 'com.example.chattr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZm6B27I1xRFVZM9lBpk7C1RPCfxJtVig',
    appId: '1:404568858266:ios:9d73521b3dbd9187234923',
    messagingSenderId: '404568858266',
    projectId: 'chattr-da2b5',
    storageBucket: 'chattr-da2b5.firebasestorage.app',
    iosBundleId: 'com.example.chattr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1e9WAJE5Hl42TY2L4DoFAA_IAGWo-pfs',
    appId: '1:404568858266:web:347e5455b1dacc6d234923',
    messagingSenderId: '404568858266',
    projectId: 'chattr-da2b5',
    authDomain: 'chattr-da2b5.firebaseapp.com',
    storageBucket: 'chattr-da2b5.firebasestorage.app',
  );
}
